#%RAML 1.0
title: Facade API
version: v1
mediaType: application/json
baseUri: https://example.com/api
uses:
  facade: facade-lib.raml

types:
  User:
    type: object
    properties:
      fullName: string
      userName: string
      password:
        (facade.remove):
        type: string
      clientIp:
        (facade.set):
          source: remote_address
        type: string

/users/{userId}:
  get:
    (facade.authorize):
      if: context.authUser.id = "123456"
    responses:
      200:
        body:
          type: User
  feed:put:
    body:
      application/json:
        type: User

/events/{path}:
  feed:put:
    (facade.rewrite):
      uri: /rewritten-events/root/{path}