#%RAML 1.0
title: Facade API
version: v1
mediaType: application/json
baseUri: https://example.com/api

types:
  Status:
    type: object
    properties:
      publicField: number
      privateField:
        (forbidden):
          if: "!context.isAuthorized"

  Conditional:
    type: object
    properties:
      if?:

annotationTypes:
  forbidden: nil | Conditional

/authorized-only-resource:
  (forbidden):
    if: "!context.isAuthorized"

/authorized-only-method:
  get:
    (forbidden):
      if: "!context.isAuthorized"

/authorized-only-fields:
  get:
    responses:
      200:
        body:
          type: Status
  feed:put:
    body:
      type: Status