#%RAML 1.0
title: Facade API
version: v1
mediaType: application/json
baseUri: https://example.com/api
uses:
  facade: facade-lib.raml

types:
  TestInnerFields:
    type: object
    properties:
      mode: string
      secret:
        (facade.remove):
        type: string

  TestRequestWithInnerFields:
    type: object
    properties:
      mode: string
      password:
        (facade.remove):
        type: string
      inner: TestInnerFields
      fetched:
        (facade.fetch):
          location: '"hb://fetch"'
          expects: document
          on_error: remove
          stages: [request,response]

  TestRequest:
    type: object
    properties:
      mode: string
      resultType: string
      clientIp:
        (facade.set):
          source: remote_address
          stages: [request]
        type: string
      password:
        (facade.remove):
        type: string

/without-annotations:
  post:
  get:
    responses:
      200:
        body:
          type: object

/request-annotations:
  post:
    (facade.rewrite):
      location: hb://test
    body:
      type: TestRequest

/request-inner-annotations:
  post:
    (facade.rewrite):
      location: hb://test
    body:
      type: TestRequestWithInnerFields

/request-with-query-string:
  get:
    queryParameters:
      test:
        type: string
        default: abc

/multiple-annotations:
  (facade.apply):
  - rewrite:
      location: hb://1
      if: "false"
  - rewrite:
      location: hb://2
      if: "true"
  - forbidden:
      if: "true"
  - forbidden:
      if: "false"
  - context_fetch:
      target: "abc"
      location: '"hb://fetch"'
      expects: document
      on_error: remove
