#%RAML 1.0
title: Facade API
version: v1
mediaType: application/json
baseUri: http://test
uses:
  facade: facade-lib.raml

types:
  SimpleService:
    type: object
    properties:
      integer_field: integer
      text_field: string

/simple-resource:
  (facade.rewrite):
    location: hb://test-service
  get:
    responses:
      200:
        body:
          type: SimpleService
  /{id}:
    (facade.rewrite):
      location: hb://test-service/{id}
    get:
      responses:
        200:
          body:
            type: SimpleService

/simple-resource-with-events:
  (facade.rewrite):
    location: hb://ws-test-service
  /unreliable-feed:
    get:
  /reliable-feed:
    get:

/resource-with-rewrite-args/{some_id}:
  (facade.rewrite):
    location: hb://test-service-with-args/{path}
    query:
      path: abc/{some_id}
